### ISSUE TITLE
OpenJDK binary path

### ISSUE THREAD

**Issue by imcitius** [andrewrothstein/ansible-kafka-broker#4]
Hi

I'm trying to use this role to install and setup kafka broker cluster.
Java is setup with dependency role ansible-openjdk. This role export JAVA_HOME and updates PATH using profile.d dropins, which is not respected by systemd.
So, kafka systemd unit cannot start because no java binary in PATH.
At the same time, I can runs script from systemd unit manually, and it works.

So what do you suggest to have PATH include java binaries under systemd?

OS is Centos 7.

Thanks.

**Comment by andrewrothstein** [comment]
can u give a try with v2.2.0 of the role that I just published to the galaxy? I had failed to update the broker systemd unit to reference the openjdk JRE when I migrated the kafka role to depend on openjdk vs the oracle jre.

**Comment by imcitius** [comment]
yeah, now it works.
Thanks for the fix!
